Feature to story, patch, task

diff --git a/git-flow-agile-story b/git-flow-agile-story
--- a/git-flow-agile-story
+++ b/git-flow-agile-story
@@ -39,23 +39,24 @@ initialize() {
 	require_git_repo
 	require_gitflow_initialized
 	gitflow_load_settings
-	PREFIX=$(git config --get gitflow.prefix.feature)
+	PREFIX=$(git config --get gitflow.prefix.story)
 
 }
 
 usage() {
 	OPTIONS_SPEC="\
-git flow feature [list]
-git flow feature start
-git flow feature finish
-git flow feature publish
-git flow feature track
-git flow feature diff
-git flow feature checkout
-git flow feature pull
-git flow feature delete
+git flow story [list]
+git flow story start
+git flow story finish
+git flow story publish
+git flow story track
+git flow story diff
+git flow story rebase
+git flow story checkout
+git flow story pull
+git flow story delete
 
-Manage your feature branches.
+Manage your story branches.
 
 For more specific help type the command followed by --help
 --
@@ -69,14 +70,14 @@ cmd_default() {
 
 cmd_list() {
 	OPTIONS_SPEC="\
-git flow feature [list] [-h] [-v]
+git flow story [list] [-h] [-v]
 
-Lists all the existing feature branches in the local repository.
+Lists all the existing story branches in the local repository.
 --
 h,help!     Show this help
 v,verbose   Verbose (more) output
 "
-	local feature_branches current_branch width branch len
+	local story_branches current_branch width branch len
 	local base develop_sha branch_sha
 
 	# Define flags
@@ -85,13 +86,13 @@ v,verbose   Verbose (more) output
 	# Parse argun=ments
 	parse_args "$@"
 
-	feature_branches=$(git_local_branches_prefixed "$PREFIX")
-	if [ -z "$feature_branches" ]; then
-		warn "No feature branches exist."
+	story_branches=$(git_local_branches_prefixed "$PREFIX")
+	if [ -z "$story_branches" ]; then
+		warn "No story branches exist."
 		warn ""
-		warn "You can start a new feature branch:"
+		warn "You can start a new story branch:"
 		warn ""
-		warn "    git flow feature start <name> [<base>]"
+		warn "    git flow story start <name> [<base>]"
 		warn ""
 		exit 0
 	fi
@@ -99,13 +100,13 @@ v,verbose   Verbose (more) output
 
 	# Determine column width first
 	width=0
-	for branch in $feature_branches; do
+	for branch in $story_branches; do
 		len=${#branch}
 		width=$(max $width $len)
 	done
 	width=$(($width+3-${#PREFIX}))
 
-	for branch in $feature_branches; do
+	for branch in $story_branches; do
 		base=$(git merge-base "$branch" "$DEVELOP_BRANCH")
 		develop_sha=$(git rev-parse "$DEVELOP_BRANCH")
 		branch_sha=$(git rev-parse "$branch")
@@ -139,7 +140,7 @@ cmd_help() {
 
 name_or_current() {
 	if [ -z "$NAME" ]; then
-		use_current_feature_branch_name
+		use_current_story_branch_name
 	fi
 }
 
@@ -166,9 +167,9 @@ parse_remote_name() {
 
 cmd_start() {
 	OPTIONS_SPEC="\
-git flow feature start [-h] [-F] <name> [<base>]
+git flow story start [-h] [-F] <name> [<base>]
 
-Start new feature <name>, optionally basing it on <base> instead of <develop>
+Start new story <name>, optionally basing it on <base> instead of <develop>
 --
 h,help!          Show this help
 showcommands!    Show git commands while executing them
@@ -180,7 +181,7 @@ F,[no]fetch      Fetch from origin before performing local operation
 	DEFINE_boolean 'fetch' false 'fetch from origin before performing local operation' F
 
 	# Override defaults with values from config
-	gitflow_override_flag_boolean   "feature.start.fetch"   "fetch"
+	gitflow_override_flag_boolean   "story.start.fetch"   "fetch"
 
 	# Parse arguments
 	parse_args "$@"
@@ -209,7 +210,7 @@ F,[no]fetch      Fetch from origin before performing local operation
 
 
 	# create branch
-	git_do checkout -b "$BRANCH" "$base" || die "Could not create feature branch '$BRANCH'."
+	git_do checkout -b "$BRANCH" "$base" || die "Could not create story branch '$BRANCH'."
 
 	run_post_hook "$NAME" "$ORIGIN" "$BRANCH" "$base"
 
@@ -218,17 +219,17 @@ F,[no]fetch      Fetch from origin before performing local operation
 	echo "- A new branch '$BRANCH' was created, based on '$base'"
 	echo "- You are now on branch '$(git_current_branch)'"
 	echo ""
-	echo "Now, start committing on your feature. When done, use:"
+	echo "Now, start committing on your story. When done, use:"
 	echo ""
-	echo "     git flow feature finish $NAME"
+	echo "     git flow story finish $NAME"
 	echo
 }
 
 cmd_finish() {
 	OPTIONS_SPEC="\
-git flow feature finish [-h] [-F] [-r] [-p] [-k] [-D] [-S] [--no-ff] <name|nameprefix>
+git flow story finish [-h] [-F] [-r] [-p] [-k] [-D] [-S] [--no-ff] <name|nameprefix>
 
-Finish feature <name>
+Finish story <name>
 --
 h,help!                Show this help
 showcommands!          Show git commands while executing them
@@ -238,8 +239,8 @@ p,[no]preserve-merges  Preserve merges while rebasing
 k,[no]keep             Keep branch after performing finish
 keepremote!        	   Keep the remote branch
 keeplocal!             Keep the local branch
-D,[no]force_delete     Force delete feature branch after finish
-S,[no]squash           Squash feature during merge
+D,[no]force_delete     Force delete story branch after finish
+S,[no]squash           Squash story during merge
 no-ff!                 Never fast-forward during the merge
 "
 	local finish_base
@@ -251,22 +252,22 @@ no-ff!                 Never fast-forward during the merge
 	DEFINE_boolean 'keep' false "keep branch after performing finish" k
 	DEFINE_boolean 'keepremote' false "keep the remote branch" R
 	DEFINE_boolean 'keeplocal' false "keep the local branch" L
-	DEFINE_boolean 'force_delete' false "force delete feature branch after finish" D
-	DEFINE_boolean 'squash' false "squash feature during merge" S
+	DEFINE_boolean 'force_delete' false "force delete story branch after finish" D
+	DEFINE_boolean 'squash' false "squash story during merge" S
 	DEFINE_boolean 'squash-info' false "add branch info during squash" I
 	DEFINE_boolean 'no-ff!' false "Don't fast-forward ever during merge " N
 
 	# Override defaults with values from config
-	gitflow_override_flag_boolean   "feature.finish.fetch"             "fetch"
-	gitflow_override_flag_boolean   "feature.finish.rebase"            "rebase"
-	gitflow_override_flag_boolean   "feature.finish.preserve-merges"   "preserve_merges"
-	gitflow_override_flag_boolean   "feature.finish.keep"              "keep"
-	gitflow_override_flag_boolean   "feature.finish.keepremote"        "keepremote"
-	gitflow_override_flag_boolean   "feature.finish.keeplocal"         "keeplocal"
-	gitflow_override_flag_boolean   "feature.finish.force-delete"      "force_delete"
-	gitflow_override_flag_boolean   "feature.finish.squash"            "squash"
-	gitflow_override_flag_boolean   "feature.finish.squash-info"       "squash_info"
-	gitflow_override_flag_boolean   "feature.finish.no-ff"             "no_ff"
+	gitflow_override_flag_boolean   "story.finish.fetch"             "fetch"
+	gitflow_override_flag_boolean   "story.finish.rebase"            "rebase"
+	gitflow_override_flag_boolean   "story.finish.preserve-merges"   "preserve_merges"
+	gitflow_override_flag_boolean   "story.finish.keep"              "keep"
+	gitflow_override_flag_boolean   "story.finish.keepremote"        "keepremote"
+	gitflow_override_flag_boolean   "story.finish.keeplocal"         "keeplocal"
+	gitflow_override_flag_boolean   "story.finish.force-delete"      "force_delete"
+	gitflow_override_flag_boolean   "story.finish.squash"            "squash"
+	gitflow_override_flag_boolean   "story.finish.squash-info"       "squash_info"
+	gitflow_override_flag_boolean   "story.finish.no-ff"             "no_ff"
 
 	# Parse arguments
 	parse_args "$@"
@@ -283,7 +284,7 @@ no-ff!                 Never fast-forward during the merge
 
 	BASE_BRANCH=$(gitflow_config_get_base_branch $BRANCH)
 	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
-	git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't finish the feature branch '$BRANCH'."
+	git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't finish the story branch '$BRANCH'."
 
 	# Detect if we're restoring from a merge conflict
 	if [ -f "$DOT_GIT_DIR/.gitflow/MERGE_BASE" ]; then
@@ -320,7 +321,7 @@ no-ff!                 Never fast-forward during the merge
 			echo "    git commit"
 			echo
 			echo "You can then complete the finish by running it again:"
-			echo "    git flow feature finish $NAME"
+			echo "    git flow story finish $NAME"
 			echo
 			exit 1
 		fi
@@ -362,11 +363,11 @@ no-ff!                 Never fast-forward during the merge
         if flag showcommands; then
             _rebase_opts="$_rebase_opts --showcommands"
         fi
-		if ! git flow-tower feature rebase $_rebase_opts "$NAME"; then
+		if ! git flow-tower story rebase $_rebase_opts "$NAME"; then
 			warn "Finish was aborted due to conflicts during rebase."
 			warn "Please finish the rebase manually now."
 			warn "When finished, re-run:"
-			warn "    git flow feature finish '$NAME' '$BASE_BRANCH'"
+			warn "    git flow story finish '$NAME' '$BASE_BRANCH'"
 			exit 1
 		fi
 	fi
@@ -386,7 +387,7 @@ no-ff!                 Never fast-forward during the merge
 	# 	fi
 	# else
 	# 	git_do merge --squash "$BRANCH"
-	# 	flag squash_info && gitflow_create_squash_message "Merged feature branch '$BRANCH'" "$BASE_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
+	# 	flag squash_info && gitflow_create_squash_message "Merged story branch '$BRANCH'" "$BASE_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
 	# 	git_do commit
 	# fi
 
@@ -402,7 +403,7 @@ no-ff!                 Never fast-forward during the merge
 		echo "    git commit"
 		echo
 		echo "You can then complete the finish by running it again:"
-		echo "    git flow feature finish $NAME"
+		echo "    git flow story finish $NAME"
 		echo
 		exit 1
 	fi
@@ -413,7 +414,7 @@ no-ff!                 Never fast-forward during the merge
 	COMPARE_URL="https://$PUSH_URL/compare/$BASE_BRANCH...$BRANCH?expand=1";
 	open $COMPARE_URL;
 
-	# When no merge conflict is detected, just clean up the feature branch
+	# When no merge conflict is detected, just clean up the story branch
 	# gitflow_config_remove_base_branch "$BRANCH"
 	helper_finish_cleanup
 }
@@ -461,7 +462,7 @@ helper_finish_cleanup() {
 
 	echo
 	echo "Summary of actions:"
-	echo "- The feature branch '$BRANCH' was pull requested into '$BASE_BRANCH'"
+	echo "- The story branch '$BRANCH' was pull requested into '$BASE_BRANCH'"
 	#echo "- Merge conflicts were resolved"		# TODO: Add this line when it's supported
 	# if noflag keep; then
 	# 	if [ $localbranchdeleted -eq $FLAGS_TRUE ]; then
@@ -480,17 +481,17 @@ helper_finish_cleanup() {
 			keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
 		fi
 	# fi
-	echo "- Feature branch '$BRANCH' "$keepmsg
+	echo "- Story branch '$BRANCH' "$keepmsg
 	echo "- You are now on branch '$(git_current_branch)'"
 	echo
 }
 
 cmd_publish() {
 	OPTIONS_SPEC="\
-git flow feature publish [-h] [<name>]
+git flow story publish [-h] [<name>]
 
-Publish feature branch <name> on $ORIGIN.
-When <name> is omitted the current branch is used, but only if it's a feature branch.
+Publish story branch <name> on $ORIGIN.
+When <name> is omitted the current branch is used, but only if it's a story branch.
 --
 h,help!          Show this help
 showcommands!    Show git commands while executing them
@@ -529,9 +530,9 @@ showcommands!    Show git commands while executing them
 
 cmd_track() {
 	OPTIONS_SPEC="\
-git flow feature track [-h] <name>
+git flow story track [-h] <name>
 
-Start tracking feature <name> that is shared on $ORIGIN
+Start tracking story <name> that is shared on $ORIGIN
 --
 h,help!          Show this help
 showcommands!    Show git commands while executing them
@@ -564,7 +565,7 @@ showcommands!    Show git commands while executing them
 
 cmd_diff() {
 	OPTIONS_SPEC="\
-git flow feature diff [-h] [<name|nameprefix>]
+git flow story diff [-h] [<name|nameprefix>]
 
 Show all changes in <name> that are not in <develop>
 --
@@ -582,7 +583,7 @@ showcommands!    Show git commands while executing them
 		git_do diff "$base..$BRANCH"
 	else
 		if ! git_current_branch | grep -q "^$PREFIX"; then
-			die "Not on a feature branch. Name one explicitly."
+			die "Not on a story branch. Name one explicitly."
 		fi
 
 		base=$(git merge-base "$DEVELOP_BRANCH" HEAD)
@@ -592,9 +593,9 @@ showcommands!    Show git commands while executing them
 
 cmd_checkout() {
 	OPTIONS_SPEC="\
-git flow feature checkout [-h] [<name|nameprefix>]
+git flow story checkout [-h] [<name|nameprefix>]
 
-Switch to feature branch <name>
+Switch to story branch <name>
 --
 h,help!          Show this help
 showcommands!    Show git commands while executing them
@@ -606,7 +607,7 @@ showcommands!    Show git commands while executing them
 		gitflow_expand_nameprefix_arg 
 		git_do checkout "$BRANCH"  || die "Could not check out branch '$BRANCH'."
 	else
-		die "Name a feature branch explicitly."
+		die "Name a story branch explicitly."
 	fi
 }
 
@@ -615,50 +616,50 @@ cmd_co() {
 	cmd_checkout "$@"
 }
 
-# cmd_rebase() {
-# 	OPTIONS_SPEC="\
-# git flow feature rebase [-h] [-i] [-p] [<name|nameprefix>]
+cmd_rebase() {
+	OPTIONS_SPEC="\
+git flow story rebase [-h] [-i] [-p] [<name|nameprefix>]
 
-# Rebase <name> on <base_branch>
-# --
-# h,help!                Show this help
-# showcommands!          Show git commands while executing them
-# i,[no]interactive      Do an interactive rebase
-# p,[no]preserve-merges  Preserve merges
-# "
-# 	local opts
+Rebase <name> on <base_branch>
+--
+h,help!                Show this help
+showcommands!          Show git commands while executing them
+i,[no]interactive      Do an interactive rebase
+p,[no]preserve-merges  Preserve merges
+"
+	local opts
 
-# 	# Define flags
-# 	DEFINE_boolean 'interactive' false 'do an interactive rebase' i
-# 	DEFINE_boolean 'preserve-merges' false 'try to recreate merges' p
+	# Define flags
+	DEFINE_boolean 'interactive' false 'do an interactive rebase' i
+	DEFINE_boolean 'preserve-merges' false 'try to recreate merges' p
 
-# 	# Override defaults with values from config
-# 	gitflow_override_flag_boolean   "feature.rebase.interactive"       "interactive"
-# 	gitflow_override_flag_boolean   "feature.rebase.preserve-merges"   "preserve_merges"
+	# Override defaults with values from config
+	gitflow_override_flag_boolean   "story.rebase.interactive"       "interactive"
+	gitflow_override_flag_boolean   "story.rebase.preserve-merges"   "preserve_merges"
 
-# 	# Parse arguments
-# 	parse_args "$@"
+	# Parse arguments
+	parse_args "$@"
 
-# 	gitflow_expand_nameprefix_arg_or_current 'feature'
+	gitflow_expand_nameprefix_arg_or_current 'story'
 
-# 	BASE_BRANCH=$(gitflow_config_get_base_branch $BRANCH)
-# 	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+	BASE_BRANCH=$(gitflow_config_get_base_branch $BRANCH)
+	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
 
-# 	warn "Will try to rebase '$NAME' which is based on '$BASE_BRANCH'..."
-# 	require_clean_working_tree
-# 	require_branch "$BRANCH"
+	warn "Will try to rebase '$NAME' which is based on '$BASE_BRANCH'..."
+	require_clean_working_tree
+	require_branch "$BRANCH"
 
-#     git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't finish the feature branch '$BRANCH'."
+    git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't finish the story branch '$BRANCH'."
 
-# 	git_do checkout -q "$BRANCH"  || die "Could not check out branch '$BRANCH'."
-# 	if flag interactive; then
-# 		opts="$opts -i"
-# 	fi
-# 	if flag preserve_merges; then
-# 		opts="$opts -p"
-# 	fi
-# 	git_do rebase $opts "$BASE_BRANCH"
-# }
+	git_do checkout -q "$BRANCH"  || die "Could not check out branch '$BRANCH'."
+	if flag interactive; then
+		opts="$opts -i"
+	fi
+	if flag preserve_merges; then
+		opts="$opts -p"
+	fi
+	git_do rebase $opts "$BASE_BRANCH"
+}
 
 avoid_accidental_cross_branch_action() {
 	local current_branch
@@ -674,9 +675,9 @@ avoid_accidental_cross_branch_action() {
 
 cmd_pull() {
 	OPTIONS_SPEC="\
-git flow feature pull [-h] <remote> [<name>]
+git flow story pull [-h] <remote> [<name>]
 
-Pull feature <name> from <remote>
+Pull story <name> from <remote>
 --
 h,help!          Show this help
 showcommands!    Show git commands while executing them
@@ -694,12 +695,12 @@ showcommands!    Show git commands while executing them
 	fi
 	name_or_current
 
-	# To avoid accidentally merging different feature branches into each other,
-	# die if the current feature branch differs from the requested $NAME
+	# To avoid accidentally merging different story branches into each other,
+	# die if the current story branch differs from the requested $NAME
 	# argument.
 	current_branch=$(git_current_branch)
 	if startswith "$current_branch" "$PREFIX"; then
-		# We are on a local feature branch already, so $BRANCH must be equal to
+		# We are on a local story branch already, so $BRANCH must be equal to
 		# the current branch
 		avoid_accidental_cross_branch_action || die
 	fi
@@ -737,9 +738,9 @@ showcommands!    Show git commands while executing them
 
 cmd_delete() {
 	OPTIONS_SPEC="\
-git flow feature delete [-h] [-f] [-r] <name>
+git flow story delete [-h] [-f] [-r] <name>
 
-Delete a given feature branch
+Delete a given story branch
 --
 h,help!          Show this help
 showcommands!    Show git commands while executing them
@@ -753,8 +754,8 @@ r,[no]remote     Delete remote branch
 	DEFINE_boolean 'remote' false "delete remote branch" r
 
 	# Override defaults with values from config
-	gitflow_override_flag_boolean   "feature.delete.force"    "force"
-	gitflow_override_flag_boolean   "feature.delete.remote"   "remote"
+	gitflow_override_flag_boolean   "story.delete.force"    "force"
+	gitflow_override_flag_boolean   "story.delete.remote"   "remote"
 
 	# Parse arguments
 	parse_args "$@"
@@ -785,7 +786,7 @@ r,[no]remote     Delete remote branch
 				git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
 			fi
 		else
-			die "Feature branch '$BRANCH' has been not been merged yet. Use -f to force the deletion."
+			die "Story branch '$BRANCH' has been not been merged yet. Use -f to force the deletion."
 		fi
 	fi
 
@@ -794,8 +795,8 @@ r,[no]remote     Delete remote branch
 
 	echo
 	echo "Summary of actions:"
-	echo "- Feature branch '$BRANCH' has been deleted."
-	flag remote && echo "- Feature branch '$BRANCH' in '$ORIGIN' has been deleted."
+	echo "- Story branch '$BRANCH' has been deleted."
+	flag remote && echo "- Story branch '$BRANCH' in '$ORIGIN' has been deleted."
 	echo "- You are now on branch '$(git_current_branch)'"
 	echo
 }
