Fixes

diff --git a/git-flow-agile-task b/git-flow-agile-task
--- a/git-flow-agile-task
+++ b/git-flow-agile-task
@@ -414,6 +414,8 @@ This will perform the following operations and build failures may occur.
 --
 h,help!          Show this help
 "
+	local antexitcode
+
 	# Parse arguments
 	parse_args "$@"
 
@@ -424,13 +426,24 @@ h,help!          Show this help
 
 	git_do checkout "$BRANCH" || die "Could not check out branch '$BRANCH'."
 
-	cd $(git rev-parse --show-toplevel)
+	cd "$(git rev-parse --show-toplevel)"
 
 	echo "============================== SETUP =============================="
 	npm install
 
 	echo "============================== LOCAL TESTS =============================="
 	grunt jasmine 
+
+	if [ $? -ne 0 ]; then
+		terminal-notifier -title "Deploy $NAME" -message "Local test failure. Deployment did not begin"
+		tput bel
+		echo
+		echo "The local Jasmine JS tests failed, so the ant deployment was not attempted"
+		echo "  Resolve the tests and then re-run the deploy command when ready"
+		echo
+		exit 1
+	fi
+
 
 	echo "============================== DEPLOY =============================="
 	(sleep 5; goto_salesforce_deploy_status) &
@@ -447,12 +460,32 @@ h,help!          Show this help
 	echo "Deploying and running all tests..."
 	echo
 	ant deployNcinoCI > /dev/null
+	antexitcode=$?
+
+
+	if [[ $antexitcode != 0 && $antexitcode != 130 ]]; then
+		terminal-notifier -title "Deploy $NAME FAILED" -message "Deployment failure. Check terminal for error message."
+		tput bel
+		echo
+		echo "Deploying to your org has failed"
+		echo "  Check the error message, resolve the issue, and re-run the deploy command when ready"
+		echo
+		exit 1
+	fi
+
+	if [[ $antexitcode == 130 ]]; then
+		echo "Deployment Cancelled"
+		echo
+	fi
+
+	terminal-notifier -title "Deploy $NAME SUCCEEDED" -message "Deployment was successful. All Apex tests passed and your org should now have the most recent code."
+	tput bel
 
 	echo
 	echo "Summary of actions:"
 	echo "- The local Jasmine JS tests were run"
-	echo "- The code was attempted to be deployed to your org"
-	echo "- All tests were attempted"
+	echo "- The code was successfully deployed to your org"
+	echo "- All tests were attempted and successful"
 	echo "- Your org's deployment status was opened in your browser"
 	echo
 	echo "- You are now on branch '$(git_current_branch)'"
