Conversion to tower fork

diff --git a/git-flow-agile-feature b/git-flow-agile-feature
--- a/git-flow-agile-feature
+++ b/git-flow-agile-feature
@@ -335,17 +335,12 @@ no-ff!                 Never fast-forward during the merge
 	# merged into the local branch
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 		git_fetch_branch "$ORIGIN" "$BRANCH"
-	else
-		cmd_publish "$NAME"
 	fi
-
 
 	# Update local branches with remote branches
 	if flag fetch; then
 		git_fetch_branch "$ORIGIN" "$BASE_BRANCH"
 	fi
-
-	git_do push "$ORIGIN" "$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
 
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
@@ -358,42 +353,41 @@ no-ff!                 Never fast-forward during the merge
 	run_pre_hook "$NAME" "$ORIGIN" "$BRANCH"
 
 	# If the user wants to rebase, do that first
-	# if flag rebase; then
- #        local _rebase_opts=""
- #        if flag preserve_merges; then
- #            _rebase_opts="$_rebase_opts -p"
- #        fi
- #        if flag showcommands; then
- #            _rebase_opts="$_rebase_opts --showcommands"
- #        fi
-	# 	if ! git flow-tower feature rebase $_rebase_opts "$NAME"; then
-	# 		warn "Finish was aborted due to conflicts during rebase."
-	# 		warn "Please finish the rebase manually now."
-	# 		warn "When finished, re-run:"
-	# 		warn "    git flow feature finish '$NAME' '$BASE_BRANCH'"
-	# 		exit 1
-	# 	fi
-	# fi
+	if flag rebase; then
+        local _rebase_opts=""
+        if flag preserve_merges; then
+            _rebase_opts="$_rebase_opts -p"
+        fi
+        if flag showcommands; then
+            _rebase_opts="$_rebase_opts --showcommands"
+        fi
+		if ! git flow-tower feature rebase $_rebase_opts "$NAME"; then
+			warn "Finish was aborted due to conflicts during rebase."
+			warn "Please finish the rebase manually now."
+			warn "When finished, re-run:"
+			warn "    git flow feature finish '$NAME' '$BASE_BRANCH'"
+			exit 1
+		fi
+	fi
 
 	# Merge into BASE
 	git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
 
-	# if noflag squash; then
-	# 	if flag no_ff; then
-	# 		git_do merge --no-ff "$BRANCH"
-	# 	else
-	# 		if [ "$(git rev-list -n2 "$BASE_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
-	# 			git_do merge --ff "$BRANCH"
-	# 		else
-	# 			git_do merge --no-ff "$BRANCH"
-	# 		fi
-	# 	fi
-	# else
-	# 	git_do merge --squash "$BRANCH"
-	# 	flag squash_info && gitflow_create_squash_message "Merged feature branch '$BRANCH'" "$BASE_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
-	# 	git_do commit
-	# fi
-
+	if noflag squash; then
+		if flag no_ff; then
+			git_do merge --no-ff "$BRANCH"
+		else
+			if [ "$(git rev-list -n2 "$BASE_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
+				git_do merge --ff "$BRANCH"
+			else
+				git_do merge --no-ff "$BRANCH"
+			fi
+		fi
+	else
+		git_do merge --squash "$BRANCH"
+		flag squash_info && gitflow_create_squash_message "Merged feature branch '$BRANCH'" "$BASE_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
+		git_do commit
+	fi
 
 	if [ $? -ne 0 ]; then
 		# Oops.. we have a merge conflict!
@@ -414,13 +408,9 @@ no-ff!                 Never fast-forward during the merge
 
 	run_post_hook "$NAME" "$ORIGIN" "$BRANCH"
 
-	PUSH_URL=$(git remote show origin | grep Push | grep -oh "github.com[\/:].*" | sed "s/github\.com\:/github.com\//g" | sed "s/\.git//g");
-	COMPARE_URL="https://$PUSH_URL/compare/$BASE_BRANCH...$BRANCH?expand=1";
-	open $COMPARE_URL;
-
 	# When no merge conflict is detected, just clean up the feature branch
-	# gitflow_config_remove_base_branch "$BRANCH"
-	# helper_finish_cleanup
+	gitflow_config_remove_base_branch "$BRANCH"
+	helper_finish_cleanup
 }
 
 helper_finish_cleanup() {
@@ -433,36 +423,36 @@ helper_finish_cleanup() {
 	remotebranchdeleted=$FLAGS_FALSE
 	localbranchdeleted=$FLAGS_FALSE
 
-	# if noflag keep; then
+	if noflag keep; then
 
-	# 	# Always delete remote first
-	# 	if noflag keepremote;then
-	# 		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-	# 			git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
-	# 		fi
-	# 	fi
+		# Always delete remote first
+		if noflag keepremote;then
+			if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+				git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
+			fi
+		fi
 
-	# 	# Delete local after remote to avoid warnings
-	# 	if noflag keeplocal; then
-	# 		if [ "$BRANCH" = "$(git_current_branch)" ]; then
-	# 			git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
-	# 		fi
-	# 		if flag force_delete; then
-	# 			git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-	# 		else
-	# 			if noflag squash; then
-	# 				git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-	# 			else
-	# 				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-	# 			fi
-	# 		fi
-	# 	fi
+		# Delete local after remote to avoid warnings
+		if noflag keeplocal; then
+			if [ "$BRANCH" = "$(git_current_branch)" ]; then
+				git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
+			fi
+			if flag force_delete; then
+				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+			else
+				if noflag squash; then
+					git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+				else
+					git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+				fi
+			fi
+		fi
 
-	# 	# no more branches: we can safely remove config section
-	# 	if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
-	# 		gitflow_config_remove_base_section "$BRANCH"
-	# 	fi
-	# fi
+		# no more branches: we can safely remove config section
+		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
+			gitflow_config_remove_base_section "$BRANCH"
+		fi
+	fi
 
 	echo
 	echo "Summary of actions:"
@@ -662,7 +652,7 @@ p,[no]preserve-merges  Preserve merges
 	if flag preserve_merges; then
 		opts="$opts -p"
 	fi
-	# git_do rebase $opts "$BASE_BRANCH"
+	git_do rebase $opts "$BASE_BRANCH"
 }
 
 avoid_accidental_cross_branch_action() {
@@ -773,28 +763,28 @@ r,[no]remote     Delete remote branch
 
 	current_branch=$(git_current_branch)
 	# We can't delete a branch we are on, switch to the develop branch.
-	# if [ "$BRANCH" = "$current_branch" ]; then
-	# 	require_clean_working_tree
-	# 	git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
-	# fi
+	if [ "$BRANCH" = "$current_branch" ]; then
+		require_clean_working_tree
+		git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+	fi
 
-	# if git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-	# 	git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
-	# 	if flag remote; then
-	# 		git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
-	# 	fi
-	# else
-	# 	if flag force; then
-	# 		git_do branch -D "$BRANCH" || die "Could not delete the $BRANCH."
-	# 		if flag remote; then
-	# 			git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
-	# 		fi
-	# 	else
-	# 		die "Feature branch '$BRANCH' has been not been merged yet. Use -f to force the deletion."
-	# 	fi
-	# fi
+	if git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
+		git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
+		if flag remote; then
+			git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+		fi
+	else
+		if flag force; then
+			git_do branch -D "$BRANCH" || die "Could not delete the $BRANCH."
+			if flag remote; then
+				git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+			fi
+		else
+			die "Feature branch '$BRANCH' has been not been merged yet. Use -f to force the deletion."
+		fi
+	fi
 
-	# gitflow_config_remove_base_section "$BRANCH"
+	gitflow_config_remove_base_section "$BRANCH"
 	run_post_hook "$NAME" "$ORIGIN" "$BRANCH"
 
 	echo
diff --git a/git-flow-agile-hotfix b/git-flow-agile-hotfix
--- a/git-flow-agile-hotfix
+++ b/git-flow-agile-hotfix
@@ -381,8 +381,6 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	# merged into the local branch
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 		git_fetch_branch "$ORIGIN" "$BRANCH"
-	else
-		cmd_publish "$NAME"
 	fi
 
 	# Update local branches with remote branches
@@ -391,13 +389,10 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 		[ "$BASE_BRANCH" = "$MASTER_BRANCH" ] && git_fetch_branch "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
 
-	git_do push "$ORIGIN" "$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
-
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
 	fi
-
 	if git_remote_branch_exists "$ORIGIN/$BASE_BRANCH"; then
 		require_branches_equal "$BASE_BRANCH" "$ORIGIN/$BASE_BRANCH"
 	fi
@@ -441,14 +436,14 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 
 	run_pre_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
 
-	# # Try to merge into BASE.
-	# # In case a previous attempt to finish this release branch has failed,
-	# # but the merge into BASE was successful, we skip it now
-	# if ! git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
-	# 	git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
-	# 	git_do merge --no-ff "$BRANCH" || die "There were merge conflicts."
-	# 	# TODO: What do we do now?
-	# fi
+	# Try to merge into BASE.
+	# In case a previous attempt to finish this release branch has failed,
+	# but the merge into BASE was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
+		git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
+		git_do merge --no-ff "$BRANCH" || die "There were merge conflicts."
+		# TODO: What do we do now?
+	fi
 
 	if noflag notag; then
 		# Try to tag the release.
@@ -474,11 +469,11 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
 		# By default we back-merge the $MASTER_BRANCH unless the user explicitly
 		# stated not to do a back-merge, in that case we use the $BRANCH.
-		# if noflag nobackmerge; then
-		# 	MERGE_BRANCH="$BASE_BRANCH"
-		# else
-		# 	MERGE_BRANCH="$BRANCH"
-		# fi
+		if noflag nobackmerge; then
+			MERGE_BRANCH="$BASE_BRANCH"
+		else
+			MERGE_BRANCH="$BRANCH"
+		fi
 
 		# Try to merge into develop.
 		# In case a previous attempt to finish this release branch has failed,
@@ -486,61 +481,53 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 		if ! git_is_branch_merged_into "$MERGE_BRANCH" "$DEVELOP_BRANCH"; then
 			git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
 
-			# if noflag nobackmerge; then
-			# 	# Accounting for 'git describe', if a release is tagged
-			# 	# we use the tag commit instead of the branch.
-			# 	if noflag notag; then
-			# 		commit="$VERSION_PREFIX$VERSION"
-			# 	else
-			# 		commit="$BASE_BRANCH"
-			# 	fi
-			# else
-			# 	commit="$BRANCH"
-			# fi
+			if noflag nobackmerge; then
+				# Accounting for 'git describe', if a release is tagged
+				# we use the tag commit instead of the branch.
+				if noflag notag; then
+					commit="$VERSION_PREFIX$VERSION"
+				else
+					commit="$BASE_BRANCH"
+				fi
+			else
+				commit="$BRANCH"
+			fi
 
-			# git_do merge --no-ff "$commit" || die "There were merge conflicts."
+			git_do merge --no-ff "$commit" || die "There were merge conflicts."
 			# TODO: What do we do now?
-			PUSH_URL=$(git remote show origin | grep Push | grep -oh "github.com[\/:].*" | sed "s/github\.com\:/github.com\//g" |sed "s/\.git//g");
-			COMPARE_URL="https://$PUSH_URL/compare/$DEVELOP_BRANCH...$BRANCH?expand=1";
-			open $COMPARE_URL;
 		fi
 	fi
 
-	git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
 	run_post_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
 
-	PUSH_URL=$(git remote show origin | grep Push | grep -oh "github.com[\/:].*" | sed "s/github\.com\:/github.com\//g" |sed "s/\.git//g");
-	COMPARE_URL="https://$PUSH_URL/compare/$BASE_BRANCH...$BRANCH?expand=1";
-	open $COMPARE_URL;
-
 	# Delete branch
-	# if noflag keep; then
+	if noflag keep; then
 
-	# 	# Always delete remote first
-	# 	if noflag keepremote;then
-	# 		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-	# 			git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
-	# 		fi
-	# 	fi
+		# Always delete remote first
+		if noflag keepremote;then
+			if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+				git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
+			fi
+		fi
 
-	# 	# Delete local after remote to avoid warnings
-	# 	if noflag keeplocal; then
-	# 		if [ "$BRANCH" = "$(git_current_branch)" ]; then
-	# 			git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
-	# 		fi
-	# 		if flag force_delete; then
-	# 			git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-	# 		else
-	# 			git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-	# 		fi
-	# 	fi
+		# Delete local after remote to avoid warnings
+		if noflag keeplocal; then
+			if [ "$BRANCH" = "$(git_current_branch)" ]; then
+				git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+			fi
+			if flag force_delete; then
+				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+			else
+				git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+			fi
+		fi
 
-	# 	# no more branches: we can safely remove config section
-	# 	if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
-	# 		gitflow_config_remove_base_section "$BRANCH"
-	# 	fi
+		# no more branches: we can safely remove config section
+		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
+			gitflow_config_remove_base_section "$BRANCH"
+		fi
 
-	# fi
+	fi
 
 	if flag push; then
 		if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
@@ -628,29 +615,29 @@ r,[no]remote          Delete remote branch
 	run_pre_hook "$VERSION" "$ORIGIN" "$BRANCH"
 
 	current_branch=$(git_current_branch)
-	# # We can't delete a branch we are on, switch to the master branch.
-	# if [ "$BRANCH" = "$current_branch" ]; then
-	# 	require_clean_working_tree
-	# 	git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
-	# fi
+	# We can't delete a branch we are on, switch to the master branch.
+	if [ "$BRANCH" = "$current_branch" ]; then
+		require_clean_working_tree
+		git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
+	fi
 
-	# if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" && git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH" ); then
-	# 	git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
-	# 	if flag remote; then
-	# 		git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
-	# 	fi
-	# else
-	# 	if flag force; then
-	# 		git_do branch -D "$BRANCH" || die "Could not delete the $BRANCH."
-	# 		if flag remote; then
-	# 			git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
-	# 		fi
-	# 	else
-	# 		die "Hotfix branch '$BRANCH' has been not been merged in branch '$MASTER_BRANCH' and/or branch '$DEVELOP_BRANCH'. Use -f to force the deletion."
-	# 	fi
-	# fi
+	if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" && git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH" ); then
+		git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
+		if flag remote; then
+			git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+		fi
+	else
+		if flag force; then
+			git_do branch -D "$BRANCH" || die "Could not delete the $BRANCH."
+			if flag remote; then
+				git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+			fi
+		else
+			die "Hotfix branch '$BRANCH' has been not been merged in branch '$MASTER_BRANCH' and/or branch '$DEVELOP_BRANCH'. Use -f to force the deletion."
+		fi
+	fi
 
-	# gitflow_config_remove_base_section "$BRANCH"
+	gitflow_config_remove_base_section "$BRANCH"
 	run_post_hook "$VERSION" "$ORIGIN" "$BRANCH"
 
 	echo
diff --git a/git-flow-agile-release b/git-flow-agile-release
--- a/git-flow-agile-release
+++ b/git-flow-agile-release
@@ -51,13 +51,9 @@ _finish_from_develop() {
 		git_fetch_branch "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
 
-	git_do push "$ORIGIN" "$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
-
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
-	# else
-	# 	cmd_publish "$NAME"
 	fi
 	if git_remote_branch_exists "$ORIGIN/$MASTER_BRANCH"; then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
@@ -77,19 +73,19 @@ _finish_from_develop() {
 
 	run_pre_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
 
-	# # Try to merge into master.
-	# # In case a previous attempt to finish this release branch has failed,
-	# # but the merge into master was successful, we skip it now
-	# if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
-	# 		git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
-	# 		if noflag squash; then
-	# 			git_do merge --no-ff "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
-	# 		else
-	# 			git_do merge --squash "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
-	# 			flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$MASTER_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
-	# 			git_do commit
-	# 		fi
-	# fi
+	# Try to merge into master.
+	# In case a previous attempt to finish this release branch has failed,
+	# but the merge into master was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+			git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
+			if noflag squash; then
+				git_do merge --no-ff "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
+			else
+				git_do merge --squash "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
+				flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$MASTER_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
+				git_do commit
+			fi
+	fi
 
 	if noflag notag; then
 		# Try to tag the release.
@@ -120,76 +116,75 @@ _finish_from_develop() {
 		merge_branch="$BRANCH"
 	fi
 
-	# # Try to merge into develop.
-	# # In case a previous attempt to finish this release branch has failed,
-	# # but the merge into develop was successful, we skip it now
-	# if ! git_is_branch_merged_into "$merge_branch" "$DEVELOP_BRANCH"; then
-	# 	git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+	# Try to merge into develop.
+	# In case a previous attempt to finish this release branch has failed,
+	# but the merge into develop was successful, we skip it now
+	if ! git_is_branch_merged_into "$merge_branch" "$DEVELOP_BRANCH"; then
+		git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
 
-	# 	if noflag nobackmerge; then
-	# 		# Accounting for 'git describe', if a release is tagged
-	# 		# we use the tag commit instead of the branch.
-	# 		if noflag notag; then
-	# 			commit="$VERSION_PREFIX$VERSION"
-	# 		else
-	# 			commit="$MASTER_BRANCH"
-	# 		fi
-	# 	else
-	# 		commit="$BRANCH"
-	# 	fi
+		if noflag nobackmerge; then
+			# Accounting for 'git describe', if a release is tagged
+			# we use the tag commit instead of the branch.
+			if noflag notag; then
+				commit="$VERSION_PREFIX$VERSION"
+			else
+				commit="$MASTER_BRANCH"
+			fi
+		else
+			commit="$BRANCH"
+		fi
 
-	# 	if noflag squash; then
-	# 		git_do merge --no-ff "$commit" || die "There were merge conflicts." # TODO: What do we do now?
-	# 	else
-	# 		git_do merge --squash "$commit" || die "There were merge conflicts." # TODO: What do we do now?
-	# 		flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$DEVELOP_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
-	# 		git_do commit
-	# 	fi
-	# fi
+		if noflag squash; then
+			git_do merge --no-ff "$commit" || die "There were merge conflicts." # TODO: What do we do now?
+		else
+			git_do merge --squash "$commit" || die "There were merge conflicts." # TODO: What do we do now?
+			flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$DEVELOP_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
+			git_do commit
+		fi
+	fi
 
-	git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
 	run_post_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
-	
-	# # Delete branch
-	# if noflag keep; then
 
-	# 	if [ "$BRANCH" = "$(git_current_branch)" ]; then
-	# 		git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
-	# 	fi
+	# Delete branch
+	if noflag keep; then
 
-	# 	# Always delete remote first
-	# 	if noflag keepremote;then
-	# 		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-	# 			git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
-	# 		fi
-	# 	fi
+		if [ "$BRANCH" = "$(git_current_branch)" ]; then
+			git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
+		fi
 
-	# 	# Delete local after remote to avoid warnings
-	# 	if noflag keeplocal; then
-	# 		if flag force_delete; then
-	# 			git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-	# 		else
-	# 			if noflag squash; then
-	# 				git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-	# 			else
-	# 				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-	# 			fi
-	# 		fi
-	# 	fi
+		# Always delete remote first
+		if noflag keepremote;then
+			if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+				git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
+			fi
+		fi
 
-	# 	# no more branches: we can safely remove config section
-	# 	if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
-	# 		gitflow_config_remove_base_section "$BRANCH"
-	# 	fi
-	# fi
+		# Delete local after remote to avoid warnings
+		if noflag keeplocal; then
+			if flag force_delete; then
+				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+			else
+				if noflag squash; then
+					git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+				else
+					git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+				fi
+			fi
+		fi
 
-	# if flag push; then
-	# 	git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
-	# 	git_do push "$ORIGIN" "$MASTER_BRANCH" || die "Could not push branch '$MASTER_BRANCH' to remote '$ORIGIN'."
-	# 	if noflag notag; then
-	# 		git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
-	# 	fi
-	# fi
+		# no more branches: we can safely remove config section
+		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
+			gitflow_config_remove_base_section "$BRANCH"
+		fi
+	fi
+
+	if flag push; then
+		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
+		git_do push "$ORIGIN" "$MASTER_BRANCH" || die "Could not push branch '$MASTER_BRANCH' to remote '$ORIGIN'."
+		if noflag notag; then
+			git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
+		fi
+	fi
 
 	echo
 	echo "Summary of actions:"
@@ -246,13 +241,9 @@ _finish_base() {
 		git_fetch_branch "$ORIGIN" "$BASE_BRANCH"
 	fi
 
-	git_do push "$ORIGIN" "$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
-
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
-	# else
-	# 	cmd_publish "$NAME"
 	fi
 	if git_remote_branch_exists "$ORIGIN/$BASE_BRANCH"; then
 		require_branches_equal "$BASE_BRANCH" "$ORIGIN/$BASE_BRANCH"
@@ -292,68 +283,67 @@ _finish_base() {
 		fi
 	fi
 
-	# merge_branch="$BRANCH"
+	merge_branch="$BRANCH"
 
-	# # Try to merge into develop.
-	# # In case a previous attempt to finish this release branch has failed,
-	# # but the merge into develop was successful, we skip it now
-	# if ! git_is_branch_merged_into "$merge_branch" "$BASE_BRANCH"; then
-	# 	git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
+	# Try to merge into develop.
+	# In case a previous attempt to finish this release branch has failed,
+	# but the merge into develop was successful, we skip it now
+	if ! git_is_branch_merged_into "$merge_branch" "$BASE_BRANCH"; then
+		git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
 
-	# 	# Accounting for 'git describe', if a release is tagged
-	# 	# we use the tag commit instead of the branch.
-	# 	if noflag notag; then
-	# 		commit="$VERSION_PREFIX$VERSION"
-	# 	else
-	# 		commit="$BRANCH"
-	# 	fi
+		# Accounting for 'git describe', if a release is tagged
+		# we use the tag commit instead of the branch.
+		if noflag notag; then
+			commit="$VERSION_PREFIX$VERSION"
+		else
+			commit="$BRANCH"
+		fi
 
-	# 	if noflag squash; then
-	# 		git_do merge --no-ff "$commit" || die "There were merge conflicts." # TODO: What do we do now?
-	# 	else
-	# 		git_do merge --squash "$commit" || die "There were merge conflicts." # TODO: What do we do now?
-	# 		flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$BASE_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
-	# 		git_do commit
-	# 	fi
-	# fi
+		if noflag squash; then
+			git_do merge --no-ff "$commit" || die "There were merge conflicts." # TODO: What do we do now?
+		else
+			git_do merge --squash "$commit" || die "There were merge conflicts." # TODO: What do we do now?
+			flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$BASE_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
+			git_do commit
+		fi
+	fi
 
-	git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
 	run_post_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
 
-	# # Delete branch
-	# if noflag keep; then
+	# Delete branch
+	if noflag keep; then
 
-	# 	# Always delete remote first
-	# 	if noflag keepremote;then
-	# 		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-	# 			git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
-	# 		fi
-	# 	fi
+		# Always delete remote first
+		if noflag keepremote;then
+			if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+				git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
+			fi
+		fi
 
-	# 	# Delete local after remote to avoid warnings
-	# 	if noflag keeplocal; then
-	# 		if [ "$BRANCH" = "$(git_current_branch)" ]; then
-	# 			git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
-	# 		fi
-	# 		if flag force_delete; then
-	# 			git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-	# 		else
-	# 			git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-	# 		fi
-	# 	fi
+		# Delete local after remote to avoid warnings
+		if noflag keeplocal; then
+			if [ "$BRANCH" = "$(git_current_branch)" ]; then
+				git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
+			fi
+			if flag force_delete; then
+				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+			else
+				git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+			fi
+		fi
 
-	# 	# no more branches: we can safely remove config section
-	# 	if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
-	# 		gitflow_config_remove_base_section "$BRANCH"
-	# 	fi
-	# fi
+		# no more branches: we can safely remove config section
+		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
+			gitflow_config_remove_base_section "$BRANCH"
+		fi
+	fi
 
-	# if flag push; then
-	# 	git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
-	# 	if noflag notag; then
-	# 		git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
-	# 	fi
-	# fi
+	if flag push; then
+		git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
+		if noflag notag; then
+			git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
+		fi
+	fi
 
 	echo
 	echo "Summary of actions:"
@@ -548,7 +538,7 @@ v,verbose!           Verbose (more) output
 	gitflow_require_version_arg
 	gitflow_config_set_base_branch $base $BRANCH
 
-	# require_no_existing_release_branches
+	require_no_existing_release_branches
 
 	# Sanity checks
 	require_clean_working_tree
@@ -672,8 +662,6 @@ S,[no]squash        Squash release during merge
 	# merged into the local branch
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 			git_fetch_branch "$ORIGIN" "$BRANCH"
-	else
-		cmd_publish "$NAME"
 	fi
 
 	if [ "$BASE_BRANCH" = "$DEVELOP_BRANCH" ]; then
@@ -681,10 +669,6 @@ S,[no]squash        Squash release during merge
 	else
 		_finish_base
 	fi
-
-	PUSH_URL=$(git remote show origin | grep Push | grep -oh "github.com[\/:].*" | sed "s/github\.com\:/github.com\//g" |sed "s/\.git//g");
-	COMPARE_URL="https://$PUSH_URL/compare/$BASE_BRANCH...$BRANCH?expand=1";
-	open $COMPARE_URL;
 }
 
 cmd_branch() {
@@ -784,19 +768,19 @@ S,[no]squash 		Squash release during merge
 
 	run_pre_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
 
-	# # Try to merge into master.
-	# # In case a previous attempt to finish this release branch has failed,
-	# # but the merge into master was successful, we skip it now
-	# if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
-	# 		git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
-	# 		if noflag squash; then
-	# 			git_do merge --no-ff "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
-	# 		else
-	# 			git_do merge --squash "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
-	# 			flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$MASTER_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
-	# 			git_do commit
-	# 		fi
-	# fi
+	# Try to merge into master.
+	# In case a previous attempt to finish this release branch has failed,
+	# but the merge into master was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+			git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
+			if noflag squash; then
+				git_do merge --no-ff "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
+			else
+				git_do merge --squash "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
+				flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$MASTER_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
+				git_do commit
+			fi
+	fi
 
 	if noflag notag; then
 		# Try to tag the release.
@@ -954,28 +938,28 @@ r,[no]remote     Delete remote branch
 
 	current_branch=$(git_current_branch)
 	# We can't delete a branch we are on, switch to the develop branch.
-	# if [ "$BRANCH" = "$current_branch" ]; then
-	# 	require_clean_working_tree
-	# 	git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
-	# fi
+	if [ "$BRANCH" = "$current_branch" ]; then
+		require_clean_working_tree
+		git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+	fi
 
-	# if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" && git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH" ); then
-	# 	git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
-	# 	if flag remote; then
-	# 		git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
-	# 	fi
-	# else
-	# 	if flag force; then
-	# 		git_do branch -D "$BRANCH" || die "Could not delete the $BRANCH."
-	# 		if flag remote; then
-	# 			git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
-	# 		fi
-	# 	else
-	# 		die "Release branch '$BRANCH' has been not been merged in branch '$MASTER_BRANCH' and/or branch '$DEVELOP_BRANCH'. Use -f to force the deletion."
-	# 	fi
-	# fi
+	if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" && git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH" ); then
+		git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
+		if flag remote; then
+			git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+		fi
+	else
+		if flag force; then
+			git_do branch -D "$BRANCH" || die "Could not delete the $BRANCH."
+			if flag remote; then
+				git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+			fi
+		else
+			die "Release branch '$BRANCH' has been not been merged in branch '$MASTER_BRANCH' and/or branch '$DEVELOP_BRANCH'. Use -f to force the deletion."
+		fi
+	fi
 
-	# gitflow_config_remove_base_section "$BRANCH"
+	gitflow_config_remove_base_section "$BRANCH"
 	run_post_hook "$VERSION" "$ORIGIN" "$BRANCH"
 
 	echo
diff --git a/git-flow-task b/git-flow-task
--- a/git-flow-task
+++ b/git-flow-task
@@ -41,11 +41,12 @@ init() {
   require_gitflow_initialized
   gitflow_load_settings
   PREFIX=$(git config --get gitflow.prefix.task)
+  STORY_PREFIX=$(git config --get gitflow.prefix.story)
 }
 
 usage() {
 	echo "usage: git flow task [list] [-v]"
-	echo "       git flow task start [-F] <name> [<base>]"
+	echo "       git flow task start [-F] <name> <story>"
 	echo "       git flow task finish [-rFkDS] [<name|nameprefix>]"
 	echo "       git flow task publish <name>"
 	echo "       git flow task track <name>"
@@ -72,7 +73,7 @@ cmd_list() {
 		warn ""
 		warn "You can start a new Task branch:"
 		warn ""
-		warn "    git flow task start <name> [<base>]"
+		warn "    git flow task start <name> <story>"
 		warn ""
 		exit 0
 	fi
@@ -125,6 +126,13 @@ cmd_help() {
 require_name_arg() {
 	if [ "$NAME" = "" ]; then
 		warn "Missing argument <name>"
+		usage
+		exit 1
+	fi
+}
+require_story_arg() {
+	if [ "$STORY" = "" ]; then
+		warn "Missing argument <story>"
 		usage
 		exit 1
 	fi
@@ -196,8 +204,10 @@ parse_remote_name() {
 cmd_start() {
 	DEFINE_boolean fetch false 'fetch from origin before performing local operation' F
 	parse_args "$@"
-	BASE=${2:-$DEVELOP_BRANCH}
+	STORY=${2}
+	BASE=$STORY_PREFIX$STORY
 	require_name_arg
+	require_story_arg
 
 	# sanity checks
 	require_branch_absent "$BRANCH"
